import cssIcon from '../Components/Nosotros/img/techSIcons/cssIcon.png';
import javascriptIcon from '../Components/Nosotros/img/techSIcons/javascriptIcon.png';
import githubIcon from '../Components/Nosotros/img/techSIcons/gitHubIcon.png';
import htmlIcon from '../Components/Nosotros/img/techSIcons/htmlIcon.png';
import javaIcon from '../Components/Nosotros/img/techSIcons/javaIcon.png';
import mysqlIcon from '../Components/Nosotros/img/techSIcons/mysqlIcon.png';
import reactIcon from '../Components/Nosotros/img/techSIcons/reactIcon.svg';
import springBootIcon from '../Components/Nosotros/img/techSIcons/springBootIcon.svg';

// import atencionAlDetalle from '../Components/Nosotros/img/softSIcons/atencionAlDetalle.png';
// import comunicacion from '../Components/Nosotros/img/softSIcons/comunicacion.png';
// import mentalidadDeCrecimiento from '../Components/Nosotros/img/softSIcons/mentalidadDeCrecimiento.png';
import perseverancia from '../Components/Nosotros/img/softSIcons/perseverancia.png';
import proactividad from '../Components/Nosotros/img/softSIcons/proactividad.png';
import responsabilidadPersonal from '../Components/Nosotros/img/softSIcons/responsabilidadPersonal.png';
import trabajoEnEquipo from '../Components/Nosotros/img/softSIcons/trabajoEnEquipo.png';
// import orientacionAFuturo from '../Components/Nosotros/img/softSIcons/orientacionAFuturo.png';




const data = [

    {
        avatar:"",
        name: 'Aura Berenice Rodríguez Belmonte',
        gitHub:"",
        linkedin:"",
        cv:"",
        headline: 'Desarrolladora Java Full Stack JR',
        aboutMe:"",
        techSOne:htmlIcon,
        techSOneTooltip:"HTML",
        techSTwo:cssIcon,
        techSTwoTooltip:"CSS",
        techSThree:javascriptIcon,
        techSThreeTooltip:"JavaScript",
        techSFour:reactIcon,
        techSFourTooltip:"React",
        techSFive: javaIcon,
        techSFiveTooltip: "Java",
        techSSix: springBootIcon,
        techSSixTooltip: "SpringBoot",
        techSSeven: mysqlIcon,
        techSSevenTooltip: "MySQL",
        techSEight: githubIcon,
        techSEightTooltip: "GitHub",
        SoftSOne:perseverancia,
        SoftSOneTooltip:"Perseverancia",
        SoftSTwo:proactividad,
        SoftSTwoTooltip:"Proactividad",
        SoftSThree:responsabilidadPersonal,
        SoftSThreeTooltip:"Responsabilidad Personal",
        SoftSFour:trabajoEnEquipo,
        SoftSFourTooltip:"Trabajo en Equipo",


    },
    {
        avatar:"https://media.licdn.com/dms/image/D5603AQHLahu40sBkaQ/profile-displayphoto-shrink_200_200/0/1676252584021?e=1683763200&v=beta&t=glMGXSVa9EyT7amPBi2BhC1NZX5GaljQU8nEPKlU2Bc",
        name: 'Asgary Nieto Terrazas ',
        gitHub:"https://github.com/asgarynt",
        linkedin:"https://www.linkedin.com/in/asgarynt/",
        cv:"",
        headline: 'Desarrollador Java Full Stack JR',
        aboutMe:"Me apasiona la tecnología, su capacidad para innovar y resolver problemas, estoy convencido de que puedo contribuir significativamente al desarrollo de proyectos y soluciones tecnológicas.",
        techSOne:htmlIcon,
        techSOneTooltip:"HTML",
        techSTwo:cssIcon,
        techSTwoTooltip:"CSS",
        techSThree:javascriptIcon,
        techSThreeTooltip:"JavaScript",
        techSFour:reactIcon,
        techSFourTooltip:"React",
        techSFive: javaIcon,
        techSFiveTooltip: "Java",
        techSSix: springBootIcon,
        techSSixTooltip: "SpringBoot",
        techSSeven: mysqlIcon,
        techSSevenTooltip: "MySQL",
        techSEight: githubIcon,
        techSEightTooltip: "GitHub",
        SoftSOne:perseverancia,
        SoftSOneTooltip:"Perseverancia",
        SoftSTwo:proactividad,
        SoftSTwoTooltip:"Proactividad",
        SoftSThree:responsabilidadPersonal,
        SoftSThreeTooltip:"Responsabilidad Personal",
        SoftSFour:trabajoEnEquipo,
        SoftSFourTooltip:"Trabajo en Equipo",

    },
    {
        avatar:"",
        name: 'Emanuel Saucedo Olvera',
        gitHub:"",
        linkedin:"",
        cv:"",
        headline: 'Desarrollador Java Full Stack JR',
        description:"",
        aboutMe:"",
        techSOne:htmlIcon,
        techSOneTooltip:"HTML",
        techSTwo:cssIcon,
        techSTwoTooltip:"CSS",
        techSThree:javascriptIcon,
        techSThreeTooltip:"JavaScript",
        techSFour:reactIcon,
        techSFourTooltip:"React",
        techSFive: javaIcon,
        techSFiveTooltip: "Java",
        techSSix: springBootIcon,
        techSSixTooltip: "SpringBoot",
        techSSeven: mysqlIcon,
        techSSevenTooltip: "MySQL",
        techSEight: githubIcon,
        techSEightTooltip: "GitHub",
        SoftSOne:perseverancia,
        SoftSOneTooltip:"Perseverancia",
        SoftSTwo:proactividad,
        SoftSTwoTooltip:"Proactividad",
        SoftSThree:responsabilidadPersonal,
        SoftSThreeTooltip:"Responsabilidad Personal",
        SoftSFour:trabajoEnEquipo,
        SoftSFourTooltip:"Trabajo en Equipo",

    },
    {
        avatar:"",
        name: 'Heber Sánchez Sánchez',
        gitHub:"",
        linkedin:"",
        cv:"",
        headline: 'Desarrollador Java Full Stack JR',
        description:"",
        aboutMe:"",
        techSOne:htmlIcon,
        techSOneTooltip:"HTML",
        techSTwo:cssIcon,
        techSTwoTooltip:"CSS",
        techSThree:javascriptIcon,
        techSThreeTooltip:"JavaScript",
        techSFour:reactIcon,
        techSFourTooltip:"React",
        techSFive: javaIcon,
        techSFiveTooltip: "Java",
        techSSix: springBootIcon,
        techSSixTooltip: "SpringBoot",
        techSSeven: mysqlIcon,
        techSSevenTooltip: "MySQL",
        techSEight: githubIcon,
        techSEightTooltip: "GitHub",
        SoftSOne:perseverancia,
        SoftSOneTooltip:"Perseverancia",
        SoftSTwo:proactividad,
        SoftSTwoTooltip:"Proactividad",
        SoftSThree:responsabilidadPersonal,
        SoftSThreeTooltip:"Responsabilidad Personal",
        SoftSFour:trabajoEnEquipo,
        SoftSFourTooltip:"Trabajo en Equipo",

    },
    {
        avatar:"",
        name: 'Hugo Morales',
        gitHub:"",
        linkedin:"",
        cv:"",
        headline: 'Desarrollador Java Full Stack JR',
        description:"",
        aboutMe:"",
        techSOne:htmlIcon,
        techSOneTooltip:"HTML",
        techSTwo:cssIcon,
        techSTwoTooltip:"CSS",
        techSThree:javascriptIcon,
        techSThreeTooltip:"JavaScript",
        techSFour:reactIcon,
        techSFourTooltip:"React",
        techSFive: javaIcon,
        techSFiveTooltip: "Java",
        techSSix: springBootIcon,
        techSSixTooltip: "SpringBoot",
        techSSeven: mysqlIcon,
        techSSevenTooltip: "MySQL",
        techSEight: githubIcon,
        techSEightTooltip: "GitHub",
        SoftSOne:perseverancia,
        SoftSOneTooltip:"Perseverancia",
        SoftSTwo:proactividad,
        SoftSTwoTooltip:"Proactividad",
        SoftSThree:responsabilidadPersonal,
        SoftSThreeTooltip:"Responsabilidad Personal",
        SoftSFour:trabajoEnEquipo,
        SoftSFourTooltip:"Trabajo en Equipo",

    }
    
]

export default data;